### ISSUE TITLE
Supported data readers and writers

### ISSUE THREAD

**Issue by roaldarbol** [animovement/aniread#3]
## Standard format
- [ ] roaldarbol/aniread#4 Movement (`csv`+`parquet`+`hdf5`)

## Indirect methods
- [x] Trackball, OF, free
- [x] Trackball, OF, fixed
- [x] roaldarbol/aniread#7 Trackball, FicTrac
- [ ] roaldarbol/aniread#11 Treadmill, rotary encoder
- [ ] #22 

### Pose estimation
- [x] roaldarbol/animovement#22 DeepLabCut ( `csv`, `hdf5`)
- [x] roaldarbol/animovement#23 SLEAP (`csv` + `hdf5`) 
- [x] roaldarbol/animovement#27 Lightning Pose ( `csv`)
- [x] roaldarbol/aniread#10 Anipose 
- [x] roaldarbol/aniread#6 FreeMoCap (`csv`)
- [ ] roaldarbol/aniread#9 ndx-pose (`nwb`/`hdf5`)

### Centroid
- [x] roaldarbol/animovement#24 TRex (`csv`)
- [x] roaldarbol/animovement#25 idtracker.ai (`csv` + `hdf5`) 
- [x] roaldarbol/animovement#26 AnimalTA (`csv`) 
- [x] roaldarbol/animovement#46 Bonsai ( `csv`)

### Bounding box
- [ ] roaldarbol/aniread#8 VGG Image Annotator (`csv`)

## Custom
- [ ] roaldarbol/aniread#5

**Comment by roaldarbol** [comment]
I don't think we need a tracking issue for this anymore.
